# Generated by Django 3.2.6 on 2021-08-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20210812_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='error',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='output',
            field=models.TextField(),
        ),
    ]
